networks: 
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 4555
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: eureka-server
    networks:
      - app-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "4555:4555"
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - app-network
    depends_on:
      - eureka-server

  # id-generation-service:
  #   build: ./id-generation-service
  #   ports:
  #     - "9090:9090"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/id_generation_database
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 4555
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  ssuper-admin-service:
    build: ./ssuper-admin-service
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ssuper_admin_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4555
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  login-service:
    build: ./login-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/login_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4555
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - ssuper-admin-service
      # - supervisor
      - admin-service
      - employee-service
      - mysql
    networks:
      - app-network

  superadmin-service:
    build: ./superadmin-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/super_admin_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4555
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  admin-service:
    build: ./admin-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/admin_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4555
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  employee-service:
    build: ./employee-service
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 4555
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  # project-service:
  #   build: ./Project-Service
  #   ports:
  #     - "8085:8085"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project_database
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 4555
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # supervisor:
  #   build: ./Supervisor
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/supervisor_database
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 4555
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # timesheet-service:
  #   build: ./Timesheet-Service
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/timesheet_database
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 4555
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # leave-request-service:
  #   build: ./LeaveRequest-Service
  #   ports:
  #     - "8087:8087"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/leaverequest_database
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: 4555
  #     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  timesheet-frontend:
    build: ./TimeSheet-frontend
    ports:
      - "3000:80"
    environment:
      - HOST=13.53.132.28
      - PORT=3000
    networks:
      - app-network

volumes:
  mysql_data:
